import json
from homeassistant.const import CONF_LANGUAGE


# Domain
DOMAIN = "lambda_heatpumps"


# Manufacturer
MANUFACTURER = "Lambda Wärmepumpen GmbH"

# Configuration
CONF_MODBUS_HOST = "modbus_host"
CONF_MODBUS_PORT = "modbus_port"
CONF_SLAVE_ID = "slave_id"
CONF_MODEL = "model"
CONF_AMOUNT_OF_HEATPUMPS = "amount_of_heatpumps"
CONF_AMOUNT_OF_BOILERS = "amount_of_boilers"
CONF_AMOUNT_OF_BUFFERS = "amount_of_buffers"
CONF_AMOUNT_OF_SOLAR = "amount_of_solar"
CONF_AMOUNT_OF_HEAT_CIRCUITS = "amount_of_heat_circuits"

DEFAULT_PORT = 502
DEFAULT_SLAVE_ID = 1



# Register definitions
# Modules:
# - General Ambient => GA
# - General E-Manager => EM
# - Heat pump (ModulNr. 1-3)
# - Boiler (ModulNr. 1-5)
# - Buffer (ModulNr. 1-5)
# - Solar (ModulNr. 1-2)


# General Ambient
GENERAL_AMBIENT_ERROR_NUMBER = 0
GENERAL_AMBIENT_OPERATING_STATE = 1
GENERAL_AMBIENT_ACTUAL_AMBIENT_TEMP = 2
GENERAL_AMBIENT_AVERAGE_AMBIENT_TEMP_1H = 3
GENERAL_AMBIENT_CALCULATED_AMBIENT_TEMP = 4

# General E-Manager
E_MANAGER_ERROR_NUMBER = 100
E_MANAGER_OPERATING_STATE = 101
E_MANAGER_ACTUAL_POWER_INPUT_OR_EXCESS = 102
E_MANAGER_ACTUAL_POWER_CONSUMPTION = 103
E_MANAGER_POWER_CONSUMPTION_SETPOINT = 104

# Heatpump 1
HEATPUMP_1_ERROR_STATE = 1000
HEATPUMP_1_ERROR_NUMBER = 1001
HEATPUMP_1_STATE = 1002
HEATPUMP_1_OPERATING_STATE = 1003
HEATPUMP_1_FLOWLINE_TEMP = 1004
HEATPUMP_1_RETURNLINE_TEMP = 1005
HEATPUMP_1_VOLUME_FLOW_HEAT_SINK = 1006
HEATPUMP_1_ENERGY_SOURCE_INLET_TEMPERATURE = 1007
HEATPUMP_1_ENERGY_SOURCE_OUTLET_TEMPERATURE = 1008
HEATPUMP_1_VOLUME_FLOW_ENERGY_SOURCE = 1009
HEATPUMP_1_COMPRESSOR_UNIT_RATING = 1010
HEATPUMP_1_ACTUAL_HEATING_CAPACITY = 1011
HEATPUMP_1_FREQUENCY_INVERTER_ACTUAL_POWER_CONSUMPTION = 1012
HEATPUMP_1_COEFFICIENT_OF_PERFORMANCE = 1013
HEATPUMP_1_PASSWORD_REGISTER = 1014
HEATPUMP_1_REQUEST_TYPE = 1015
HEATPUMP_1_REQUEST_FLOW_LINE_TEMP = 1016
HEATPUMP_1_REQUEST_RETURN_LINE_TEMP = 1017
HEATPUMP_1_REQUEST_HEAT_SINK_TEMP_DIFF = 1018
HEATPUMP_1_RELAIS_STATE_2ND_HEATING_STAGE = 1019
HEATPUMP_1_ACCUMULATED_ELECTRICAL_ENERGY_CONSUMPTION_OF_COMPRESSOR_UNIT = 1020
HEATPUMP_1_ACCUMULATED_THERMAL_ENERGY_OUTPUT_OF_COMPRESSOR_UNIT = 1021
HEATPUMP_1_QUIT_ALL_ACTIVE_HEAT_PUMP_ERRORS = 1050

# Heatpump 2
HEATPUMP_2_ERROR_STATE = 1100
HEATPUMP_2_ERROR_NUMBER = 1101
HEATPUMP_2_STATE = 1102
HEATPUMP_2_OPERATING_STATE = 1103
HEATPUMP_2_FLOWLINE_TEMP = 1104
HEATPUMP_2_RETURNLINE_TEMP = 1105
HEATPUMP_2_VOLUME_FLOW_HEAT_SINK = 1106
HEATPUMP_2_ENERGY_SOURCE_INLET_TEMPERATURE = 1107
HEATPUMP_2_ENERGY_SOURCE_OUTLET_TEMPERATURE = 1108
HEATPUMP_2_VOLUME_FLOW_ENERGY_SOURCE = 1109
HEATPUMP_2_COMPRESSOR_UNIT_RATING = 1110
HEATPUMP_2_ACTUAL_HEATING_CAPACITY = 1111
HEATPUMP_2_FREQUENCY_INVERTER_ACTUAL_POWER_CONSUMPTION = 1112
HEATPUMP_2_COEFFICIENT_OF_PERFORMANCE = 1113
HEATPUMP_2_PASSWORD_REGISTER = 1114
HEATPUMP_2_REQUEST_TYPE = 1115
HEATPUMP_2_REQUEST_FLOW_LINE_TEMP = 1116
HEATPUMP_2_REQUEST_RETURN_LINE_TEMP = 1117
HEATPUMP_2_REQUEST_HEAT_SINK_TEMP_DIFF = 1118
HEATPUMP_2_RELAIS_STATE_2ND_HEATING_STAGE = 1119
HEATPUMP_2_ACCUMULATED_ELECTRICAL_ENERGY_CONSUMPTION_OF_COMPRESSOR_UNIT = 1120
HEATPUMP_2_ACCUMULATED_THERMAL_ENERGY_OUTPUT_OF_COMPRESSOR_UNIT = 1121
HEATPUMP_2_QUIT_ALL_ACTIVE_HEAT_PUMP_ERRORS = 1150

# Heatpump 3
HEATPUMP_3_ERROR_STATE = 1200
HEATPUMP_3_ERROR_NUMBER = 1201
HEATPUMP_3_STATE = 1202
HEATPUMP_3_OPERATING_STATE = 1203
HEATPUMP_3_FLOWLINE_TEMP = 1204
HEATPUMP_3_RETURNLINE_TEMP = 1205
HEATPUMP_3_VOLUME_FLOW_HEAT_SINK = 1206
HEATPUMP_3_ENERGY_SOURCE_INLET_TEMPERATURE = 1207
HEATPUMP_3_ENERGY_SOURCE_OUTLET_TEMPERATURE = 1208
HEATPUMP_3_VOLUME_FLOW_ENERGY_SOURCE = 1209
HEATPUMP_3_COMPRESSOR_UNIT_RATING = 1210
HEATPUMP_3_ACTUAL_HEATING_CAPACITY = 1211
HEATPUMP_3_FREQUENCY_INVERTER_ACTUAL_POWER_CONSUMPTION = 1212
HEATPUMP_3_COEFFICIENT_OF_PERFORMANCE = 1213
HEATPUMP_3_PASSWORD_REGISTER = 1214
HEATPUMP_3_REQUEST_TYPE = 1215
HEATPUMP_3_REQUEST_FLOW_LINE_TEMP = 1216
HEATPUMP_3_REQUEST_RETURN_LINE_TEMP = 1217
HEATPUMP_3_REQUEST_HEAT_SINK_TEMP_DIFF = 1218
HEATPUMP_3_RELAIS_STATE_2ND_HEATING_STAGE = 1219
HEATPUMP_3_ACCUMULATED_ELECTRICAL_ENERGY_CONSUMPTION_OF_COMPRESSOR_UNIT = 1220
HEATPUMP_3_ACCUMULATED_THERMAL_ENERGY_OUTPUT_OF_COMPRESSOR_UNIT = 1221
HEATPUMP_3_QUIT_ALL_ACTIVE_HEAT_PUMP_ERRORS = 1250

# Boiler 1
BOILER_1_ERROR_NUMBER = 2000
BOILER_1_OPERATING_STATE = 2001
BOILER_1_ACTUAL_TEMPERATURE_BOILER_HIGH_SENSOR = 2002
BOILER_1_ACTUAL_TEMPERATURE_BOILER_LOW_SENSOR = 2003
BOILER_1_SETTING_FOR_MAXIMUM_BOILER_TEMPERATURE = 2050

# Boiler 2
BOILER_2_ERROR_NUMBER = 2100
BOILER_2_OPERATING_STATE = 2101
BOILER_2_ACTUAL_TEMPERATURE_BOILER_HIGH_SENSOR = 2102
BOILER_2_ACTUAL_TEMPERATURE_BOILER_LOW_SENSOR = 2103
BOILER_2_SETTING_FOR_MAXIMUM_BOILER_TEMPERATURE = 2150

# Boiler 3
BOILER_3_ERROR_NUMBER = 2200        
BOILER_3_OPERATING_STATE = 2201
BOILER_3_ACTUAL_TEMPERATURE_BOILER_HIGH_SENSOR = 2202
BOILER_3_ACTUAL_TEMPERATURE_BOILER_LOW_SENSOR = 2203
BOILER_3_SETTING_FOR_MAXIMUM_BOILER_TEMPERATURE = 2250 

# Boiler 4
BOILER_4_ERROR_NUMBER = 2300
BOILER_4_OPERATING_STATE = 2301
BOILER_4_ACTUAL_TEMPERATURE_BOILER_HIGH_SENSOR = 2302
BOILER_4_ACTUAL_TEMPERATURE_BOILER_LOW_SENSOR = 2303
BOILER_4_SETTING_FOR_MAXIMUM_BOILER_TEMPERATURE = 2350

# Boiler 5
BOILER_5_ERROR_NUMBER = 2400
BOILER_5_OPERATING_STATE = 2401
BOILER_5_ACTUAL_TEMPERATURE_BOILER_HIGH_SENSOR = 2402
BOILER_5_ACTUAL_TEMPERATURE_BOILER_LOW_SENSOR = 2403
BOILER_5_SETTING_FOR_MAXIMUM_BOILER_TEMPERATURE = 2450

# Buffer 1
BUFFER_1_ERROR_NUMBER = 3000
BUFFER_1_OPERATING_STATE = 3001
BUFFER_1_ACTUAL_TEMPERATURE_BUFFER_HIGH_SENSOR = 3002
BUFFER_1_ACTUAL_TEMPERATURE_BUFFER_LOW_SENSOR = 3003
BUFFER_1_SETTING_FOR_MAXIMUM_BUFFER_TEMPERATURE = 3050

# Buffer 2
BUFFER_2_ERROR_NUMBER = 3100
BUFFER_2_OPERATING_STATE = 3101
BUFFER_2_ACTUAL_TEMPERATURE_BUFFER_HIGH_SENSOR = 3102
BUFFER_2_ACTUAL_TEMPERATURE_BUFFER_LOW_SENSOR = 3103
BUFFER_2_SETTING_FOR_MAXIMUM_BUFFER_TEMPERATURE = 3150

# Buffer 3
BUFFER_3_ERROR_NUMBER = 3200
BUFFER_3_OPERATING_STATE = 3201
BUFFER_3_ACTUAL_TEMPERATURE_BUFFER_HIGH_SENSOR = 3202
BUFFER_3_ACTUAL_TEMPERATURE_BUFFER_LOW_SENSOR = 3203
BUFFER_3_SETTING_FOR_MAXIMUM_BUFFER_TEMPERATURE = 3250

# Buffer 4
BUFFER_4_ERROR_NUMBER = 3300
BUFFER_4_OPERATING_STATE = 3301
BUFFER_4_ACTUAL_TEMPERATURE_BUFFER_HIGH_SENSOR = 3302
BUFFER_4_ACTUAL_TEMPERATURE_BUFFER_LOW_SENSOR = 3303
BUFFER_4_SETTING_FOR_MAXIMUM_BUFFER_TEMPERATURE = 3350

# Buffer 5
BUFFER_5_ERROR_NUMBER = 3400
BUFFER_5_OPERATING_STATE = 3401
BUFFER_5_ACTUAL_TEMPERATURE_BUFFER_HIGH_SENSOR = 3402
BUFFER_5_ACTUAL_TEMPERATURE_BUFFER_LOW_SENSOR = 3403
BUFFER_5_SETTING_FOR_MAXIMUM_BUFFER_TEMPERATURE = 3450

# Solar 1
SOLAR_1_ERROR_NUMBER = 4000
SOLAR_1_OPERATING_STATE = 4001
SOLAR_1_COLLECTOR_TEMP = 4002
SOLAR_1_BUFFER_1_TEMP = 4003
SOLAR_1_BUFFER_2_TEMP = 4004
SOLAR_1_SETTING_FOR_MAXIMUM_BUFFER_TEMPERATURE = 4050
SOLAR_1_SETTING_FOR_BUFFER_CHANGEOVER_TEMPERATURE = 4051

# Solar 2
SOLAR_2_ERROR_NUMBER = 4100 
SOLAR_2_OPERATING_STATE = 4101
SOLAR_2_COLLECTOR_TEMP = 4102
SOLAR_2_BUFFER_1_TEMP = 4104
SOLAR_2_BUFFER_2_TEMP = 4105
SOLAR_2_SETTING_FOR_MAXIMUM_BUFFER_TEMPERATURE = 4150
SOLAR_2_SETTING_FOR_BUFFER_CHANGEOVER_TEMPERATURE = 4151

# Heating Circuit 1
HEATING_CIRCUIT_1_ERROR_NUMBER = 5000
HEATING_CIRCUIT_1_OPERATING_STATE = 5001
HEATING_CIRCUIT_1_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5002
HEATING_CIRCUIT_1_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5003
HEATING_CIRCUIT_1_ACTUAL_TEMPERATURE_ROOM_DEVICE_SENSOR = 5004
HEATING_CIRCUIT_1_SETPOINT_TEMPERATURE_FLOW_LINE = 5005
HEATING_CIRCUIT_1_OPERATING_MODE = 5006
HEATING_CIRCUIT_1_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5050
HEATING_CIRCUIT_1_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5051
HEATING_CIRCUIT_1_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5052

# Heating Circuit 2
HEATING_CIRCUIT_2_ERROR_NUMBER = 5100
HEATING_CIRCUIT_2_OPERATING_STATE = 5101
HEATING_CIRCUIT_2_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5102
HEATING_CIRCUIT_2_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5103
HEATING_CIRCUIT_2_ACTUAL_TEMPERATURE_ROOM_DEVICE_SENSOR = 5104
HEATING_CIRCUIT_2_SETPOINT_TEMPERATURE_FLOW_LINE = 5105
HEATING_CIRCUIT_2_OPERATING_MODE = 5106
HEATING_CIRCUIT_2_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5150
HEATING_CIRCUIT_2_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5151
HEATING_CIRCUIT_2_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5152

# Heating Circuit 3
HEATING_CIRCUIT_3_ERROR_NUMBER = 5200
HEATING_CIRCUIT_3_OPERATING_STATE = 5201
HEATING_CIRCUIT_3_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5202
HEATING_CIRCUIT_3_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5203
HEATING_CIRCUIT_3_ACTUAL_TEMPERATURE_ROOM_DEVICE_SENSOR = 5204
HEATING_CIRCUIT_3_SETPOINT_TEMPERATURE_FLOW_LINE = 5205
HEATING_CIRCUIT_3_OPERATING_MODE = 5206
HEATING_CIRCUIT_3_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5250
HEATING_CIRCUIT_3_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5251
HEATING_CIRCUIT_3_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5252

# Heating Circuit 4
HEATING_CIRCUIT_4_ERROR_NUMBER = 5300
HEATING_CIRCUIT_4_OPERATING_STATE = 5301
HEATING_CIRCUIT_4_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5302
HEATING_CIRCUIT_4_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5303
HEATING_CIRCUIT_4_ACTUAL_TEMPERATURE_ROOM_DEVICE_SENSOR = 5304
HEATING_CIRCUIT_4_SETPOINT_TEMPERATURE_FLOW_LINE = 5305
HEATING_CIRCUIT_4_OPERATING_MODE = 5306
HEATING_CIRCUIT_4_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5350
HEATING_CIRCUIT_4_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5351
HEATING_CIRCUIT_4_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5352

# Heating Circuit 5
HEATING_CIRCUIT_5_ERROR_NUMBER = 5400
HEATING_CIRCUIT_5_OPERATING_STATE = 5401
HEATING_CIRCUIT_5_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5402
HEATING_CIRCUIT_5_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5403
HEATING_CIRCUIT_5_SETPOINT_TEMPERATURE_FLOW_LINE = 5404
HEATING_CIRCUIT_5_OPERATING_MODE = 5406
HEATING_CIRCUIT_5_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5450
HEATING_CIRCUIT_5_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5451
HEATING_CIRCUIT_5_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5452


# Heating Circuit 6
HEATING_CIRCUIT_6_ERROR_NUMBER = 5500
HEATING_CIRCUIT_6_OPERATING_STATE = 5501
HEATING_CIRCUIT_6_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5502
HEATING_CIRCUIT_6_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5503
HEATING_CIRCUIT_6_ACTUAL_TEMPERATURE_ROOM_DEVICE_SENSOR = 5504
HEATING_CIRCUIT_6_SETPOINT_TEMPERATURE_FLOW_LINE = 5505
HEATING_CIRCUIT_6_OPERATING_MODE = 5506
HEATING_CIRCUIT_6_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5550
HEATING_CIRCUIT_6_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5551
HEATING_CIRCUIT_6_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5552

# Heating Circuit 7
HEATING_CIRCUIT_7_ERROR_NUMBER = 5600
HEATING_CIRCUIT_7_OPERATING_STATE = 5601
HEATING_CIRCUIT_7_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5602
HEATING_CIRCUIT_7_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5603
HEATING_CIRCUIT_7_SETPOINT_TEMPERATURE_FLOW_LINE = 5604
HEATING_CIRCUIT_7_OPERATING_MODE = 5606
HEATING_CIRCUIT_7_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5650
HEATING_CIRCUIT_7_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5651
HEATING_CIRCUIT_7_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5652

# Heating Circuit 8
HEATING_CIRCUIT_8_ERROR_NUMBER = 5700
HEATING_CIRCUIT_8_OPERATING_STATE = 5701
HEATING_CIRCUIT_8_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5702
HEATING_CIRCUIT_8_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5703
HEATING_CIRCUIT_8_SETPOINT_TEMPERATURE_FLOW_LINE = 5704
HEATING_CIRCUIT_8_OPERATING_MODE = 5706
HEATING_CIRCUIT_8_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5750
HEATING_CIRCUIT_8_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5751
HEATING_CIRCUIT_8_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5752

# Heating Circuit 9
HEATING_CIRCUIT_9_ERROR_NUMBER = 5800
HEATING_CIRCUIT_9_OPERATING_STATE = 5801
HEATING_CIRCUIT_9_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5802
HEATING_CIRCUIT_9_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5803
HEATING_CIRCUIT_9_SETPOINT_TEMPERATURE_FLOW_LINE = 5804
HEATING_CIRCUIT_9_SETPOINT_TEMPERATURE_RETURN_LINE = 5805
HEATING_CIRCUIT_9_OPERATING_MODE = 5806
HEATING_CIRCUIT_9_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5850
HEATING_CIRCUIT_9_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5851
HEATING_CIRCUIT_9_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5852

# Heating Circuit 10
HEATING_CIRCUIT_10_ERROR_NUMBER = 5900
HEATING_CIRCUIT_10_OPERATING_STATE = 5901
HEATING_CIRCUIT_10_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 5902
HEATING_CIRCUIT_10_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 5903
HEATING_CIRCUIT_10_SETPOINT_TEMPERATURE_FLOW_LINE = 5904
HEATING_CIRCUIT_10_SETPOINT_TEMPERATURE_RETURN_LINE = 5905
HEATING_CIRCUIT_10_OPERATING_MODE = 5906
HEATING_CIRCUIT_10_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 5950
HEATING_CIRCUIT_10_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 5951
HEATING_CIRCUIT_10_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 5952

# Heating Circuit 11
HEATING_CIRCUIT_11_ERROR_NUMBER = 51000
HEATING_CIRCUIT_11_OPERATING_STATE = 51001
HEATING_CIRCUIT_11_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 51002
HEATING_CIRCUIT_11_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 51003
HEATING_CIRCUIT_11_SETPOINT_TEMPERATURE_FLOW_LINE = 51004
HEATING_CIRCUIT_11_SETPOINT_TEMPERATURE_RETURN_LINE = 51005
HEATING_CIRCUIT_11_OPERATING_MODE = 51006
HEATING_CIRCUIT_11_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 51050
HEATING_CIRCUIT_11_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 51051
HEATING_CIRCUIT_11_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 51052

# Heating Circuit 12
HEATING_CIRCUIT_12_ERROR_NUMBER = 51100
HEATING_CIRCUIT_12_OPERATING_STATE = 51101
HEATING_CIRCUIT_12_ACTUAL_TEMPERATURE_FLOW_LINE_SENSOR = 51102
HEATING_CIRCUIT_12_ACTUAL_TEMPERATURE_RETURN_LINE_SENSOR = 51103
HEATING_CIRCUIT_12_SETPOINT_TEMPERATURE_FLOW_LINE = 51104
HEATING_CIRCUIT_12_SETPOINT_TEMPERATURE_RETURN_LINE = 51105
HEATING_CIRCUIT_12_OPERATING_MODE = 51106
HEATING_CIRCUIT_12_SETTING_FOR_FLOW_LINE_TEMPERATURE_SETPOINT_OFFSET = 51150
HEATING_CIRCUIT_12_SETTING_FOR_HEATING_MODE_ROOM_SETPOINT_TEMPERATURE = 51151
HEATING_CIRCUIT_12_SETTING_FOR_COOLING_MODE_ROOM_SETPOINT_TEMPERATURE = 51152



async def async_get_translation(hass, key, language="en"):
    translations = await async_get_translations(hass, language, DOMAIN)
    return translations.get(key, key)


def get_operating_states(language="en"):
    # Beispielhafte Zustände, diese sollten entsprechend der tatsächlichen Zustände angepasst werden
    states = {
        0: "OFF",
        1: "AUTOMATIC",
        2: "MANUAL",
        3: "ERROR"
    }
    return states